# Generated by Django 3.0.8 on 2020-08-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='table_name',
            new_name='content_type',
        ),
    ]
