# Generated by Django 3.0.8 on 2020-08-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200802_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='course_id',
            new_name='object_id',
        ),
    ]
